# Generated by Django 2.2 on 2019-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualInterestRate', models.FloatField(default=1.07)),
                ('monthlyAmount', models.FloatField(default=1500)),
                ('initialCapital', models.FloatField(default=10000)),
                ('carPrice', models.FloatField(default=71228)),
                ('carLoanAnnualInterestRate', models.FloatField(default=1.019)),
                ('monthlyCarLoanPayment', models.FloatField(default=614)),
                ('payWithInitialCapital', models.BooleanField(default=False)),
            ],
        ),
    ]
