# Generated by Django 2.2 on 2019-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='years',
            field=models.IntegerField(default=10),
        ),
    ]
