# Generated by Django 2.2 on 2019-04-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_investmentmodel_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='payCarLoanAfter5Years',
            field=models.BooleanField(default=False),
        ),
    ]
