# Generated by Django 2.2 on 2019-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_investmentmodel_paycarloanafter5years'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='apartmentLoan',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='investmentmodel',
            name='apartmentLoanAnnualInterestRate',
            field=models.FloatField(default=1.0125),
        ),
        migrations.AddField(
            model_name='investmentmodel',
            name='monthlyApartmentLoanPayment',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='investmentmodel',
            name='monthlyAmount',
            field=models.FloatField(default=2000),
        ),
    ]
