# Generated by Django 2.2 on 2019-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0004_auto_20190422_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmodel',
            name='spousePaysEqualAmount',
            field=models.BooleanField(default=False),
        ),
    ]
